没找到override的时候报错退出

diff --git a/.bin/sbatchoverride b/.bin/sbatchoverride
--- a/.bin/sbatchoverride
+++ b/.bin/sbatchoverride
@@ -52,8 +52,9 @@ for option in "$@"; do
         # Replace the existing parameter value
         sed -i "s|^#SBATCH\s\+--$PARAM_NAME=.*|#SBATCH --$PARAM_NAME=$PARAM_VALUE|" "$SBATCH_FILE"
     else
-        # Add the parameter if it does not exist
-        echo "#SBATCH --$PARAM_NAME=$PARAM_VALUE" >> "$SBATCH_FILE"
+        # exit with error
+        echo "Error: Parameter '--$PARAM_NAME' not found in $SBATCH_FILE."
+        exit 1
     fi
 
 done
